if: branch = master
language: node_js
node_js: 8.9.4
dist: trusty

before_install:
  - npm i yarn@latest --no-save

install: 
  - make install

before_script:
  - make build
  - make lint

script:
  - make deploy

notifications:
  email: false
  slack: lnmpy:LSbevEhQZLylhk2zozsnR286
